name: Ejecutar Scraper y Guardar Datos

on:
  push:
    branches: [ main ]
  workflow_dispatch:      # <--- AÑADE ESTA LÍNEA
  schedule:
    - cron: '0 0 * * *'
jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: write # Permiso crucial para que GitHub pueda subir el archivo

    steps:
    - name: Checkout del código
      uses: actions/checkout@v3

    - name: Configurar Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.9'
        

    - name: Ejecutar Scraper de Titulos
      run: python scraper.py
        

    - name: jecutar Auditoría de Seguridad OWASP
      run: python security_scan.py

    - name: Configurar Git y subir cambios
      run: |
        git config --global user.name "github-actions[bot]"
        git config --global user.email "github-actions[bot]@users.noreply.github.com"
        git add resultados_scraper.csv
        git commit -m "Actualización automática de datos: $(date)" || echo "No hay cambios para subir"
        git push